### ISSUE TITLE
Safari browser caused downloaded files to be garbled

### ISSUE THREAD

**Issue by jungle-boogie** [Yahweasel/ennuicastr-server#7]
Hey there,

My step-dad and I tried out your service. He has a mac and used the Safari browser. Everything worked well, once he selected the proper input in the Sound control panel thing.

However on download of the files, his side of the recording is really terribly garbled and basically unintelligible. It doesn't seem to matter the file type, either.

My interface was a sound devices usbpre2 and his was a Presonus audiobox 96. I suppose the next thing I'll do is talk him into using Firefox.

Do you know of any issues with Safari and ecaster?

Thanks!

**Comment by Yahweasel** [comment]
Safari support is pretty dubious; its audio processing APIs are not exactly up to date. At last I checked it did work tho. Would you mind giving me the recording ID (the part after i= in the download URL)? I definitely won't be able to fix anything, but I may at least be able to investigate further.

It works best in Firefox, and works in Chrome and Chromealikes.

**Comment by jungle-boogie** [comment]
Hi @Yahweasel,

Thanks for the fast reply.

I understand about not being able to fix this, as this is probably a fundamental design decision in the browser itself.

> Would you mind giving me the recording ID (the part after i= in the download URL)?

812q5w

Thanks!

**Comment by Yahweasel** [comment]
As of commit b83db16ff6e94d7f53de97f67078ae2b83173663 of ennuicastr (the client, not the server), it now works on Safari (thanks to an unbelievably generous user donating a MacBook for me to test and debug on). I haven't tested it on iOS, but as this bug was for a Mac, I believe the situation is resolved.

**Comment by jungle-boogie** [comment]
Thank you! I'll test this out soon.

The commit:
https://github.com/Yahweasel/ennuicastr/commit/b83db16ff6e94d7f53de97f67078ae2b83173663
