### ISSUE TITLE
Missing a License

### ISSUE THREAD

**Issue by 10leej** [Yahweasel/ennuicastr-server#8]
Under US law that makes this application All Right Reserved while in other parts of the world it's barely better than public domain.  
Please add a license so we can understand distribution rights which are also needed for pull requests on github which requires forking/copying this repo first unless you'd rather we share patch files.

**Comment by Yahweasel** [comment]
Here is the LICENSE file I've just added, which in no way changes the licensing status of this repository:

```
ISC.

The actual text of the license is in the header of each file. License text is
kept there instead of here because it's very easy for a LICENSE file to become
out of sync with the actual licensed code (in fact, almost inevitable). It is
poor practice to keep license information for code in a separate file from the
code it licenses.

This LICENSE file is here because some people are comforted by its presence.
```

**Comment by 10leej** [comment]
I guess I could've just checked the header of each file.
